<div class="content-wrapper" style="min-height: 900px;">
			<!-- Content Header (Page header) -->
			<section class="content-header">
			  <h1>
				Sales List Page
				<small>Preview of monthly sales</small>
			  </h1>
			  <ol class="breadcrumb">
				<li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
				<li class="active">List Page</li>
			  </ol>
			</section>
			
			<!-- Main content -->
			<section class="content">
				<div class="row">
					<div class="col-md-6">
						<div class="box">
							<div class="box-header">
							  <h3 class="box-title">Current Month Sales</h3>
							</div><!-- /.box-header -->
							<div class="box-body">
							  <table class="table table-bordered">
								<tbody><tr>
								  <th style="width: 10px">Id</th>
								  <th>Manager Name</th>
								  <th class="text-center">Sales %</th>
								  <th style="width: 40px">Zipcode</th>
								</tr>
								<tr>
								  <td>105</td>
								  <td>James</td>
								  <td class="text-center">
									72
								  </td>
								  <td>36016</td>
								</tr>
								<tr>
								  <td>102</td>
								  <td>Williams</td>
								  <td class="text-center">
									57
								  </td>
								  <td>36048</td>
								</tr>
								<tr>
								  <td>129</td>
								  <td>Peter</td>
								  <td class="text-center">
									84
								  </td>
								  <td>56225</td>
								</tr>
								<tr>
								  <td>185</td>
								  <td>Mark</td>
								  <td class="text-center">
									20
								  </td>
								  <td>5444</td>
								</tr>
								<tr>
								  <td>166</td>
								  <td>Helen</td>
								  <td class="text-center">
									20
								  </td>
								  <td>83025</td>
								</tr>
								
								<tr>
								  <td>112</td>
								  <td>Susen</td>
								  <td class="text-center">
									- 10
								  </td>
								  <td>47638</td>
								</tr>
								<tr>
								  <td>156</td>
								  <td>Rosely</td>
								  <td class="text-center">
									-60
								  </td>
								  <td>27906</td>
								</tr>
								<tr>
								  <td>26</td>
								  <td>Jasmine</td>
								  <td class="text-center">
									54
								  </td>
								  <td>47620</td>
								</tr>
								<tr>
								  <td>100</td>
								  <td>Albert</td>
								  <td class="text-center">
									20
								  </td>
								  <td>83025</td>
								</tr>
								
							  </tbody></table>
							</div><!-- /.box-body -->
							
						  </div>
					</div>
				</div>
			</section>
		</div>