<div class="layout-top-nav">
	<div class="wrapper">
		<header class="main-header">               
			<nav class="navbar navbar-static-top">
			  <div class="container-fluid">
				  <div class="navbar-header">
					<a href="#" class="navbar-brand"><b>Test</b>App</a>
					<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
					  <i class="fa fa-bars"></i>
					</button>
				  </div>

				  <div class="collapse navbar-collapse" id="navbar-collapse">            
					<ul class="nav navbar-nav navbar-right">
					  <li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello Administrator! <span class="caret"></span></a>
						<ul class="dropdown-menu" role="menu">
						  <li><a href="logout">Logout</a></li>
						</ul>
					  </li>
					</ul>
				  </div><!-- /.navbar-collapse -->
			  </div><!-- /.container-fluid -->
			</nav>
		</header>