<!-- application/layouts/scripts/layout.phtml -->
<?php echo $this->doctype() ?>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>TestApp</title>
  <?php echo $this->headLink()->setStylesheet('css/bootstrap.css') ?>
  <?php echo $this->headLink()->setStylesheet('css/font-awesome.min.css') ?>
  <?php echo $this->headLink()->setStylesheet('css/testapp.css') ?>
  <?php echo $this->headScript()->setFile( "js/jquery.min.js", $type = 'text/javascript' ) ?>
  <?php echo $this->headScript()->setFile( "js/bootstrap.min.js", $type = 'text/javascript' ) ?>
  
</head>
<body>


	<?php 
		// PHP 5.3 and later:
		
		// Checking the URL having string "login" or not 
		$pos = strrpos($_SERVER['REQUEST_URI'], "login");
		if ($pos === false) { 
			echo $this->render('header.phtml');
			echo $this->layout()->content;
			echo $this->render('footer.phtml');
		}
		else{
			echo $this->layout()->content;
		}
	?>